### PR TITLE
Faster coco eval support

### PR DESCRIPTION
**Pull request by MiXaiLL76**
https://github.com/Peterande/D-FINE/pull/27

After changing and working with .pre-commit-config, it is easier to create a new PR than to modify the old one)

In general, you can check my code after the release of faster-coco-eval==1.6.5.
I am currently preparing packages
https://github.com/MiXaiLL76/faster_coco_eval/actions/runs/11652636914

It will be cool if my library will work in multigpu validation. Before this repository, no one tried to use the library in this way)

### CODE REVIEW

**Comment by MiXaiLL76** [comment]
# Test code

```bash
CUDA_VISIBLE_DEVICES=0, torchrun --master_port=7777 --nproc_per_node=1 train.py -c configs/dfine/dfine_hgnetv2_s_coco.yml --test-only -r dfine_s_coco.pth
```

# Test out

изображение

**Comment by Peterande** [comment]
If I test with more than 1 GPU, I get an error:

```
[rank0]:   File "/home/code/D-FINE-master/src/solver/det_engine.py", line 161, in evaluate
[rank0]:     coco_evaluator.synchronize_between_processes()
[rank0]:   File "/home/code/D-FINE-master/src/data/dataset/coco_eval.py", line 64, in synchronize_between_processes
[rank0]:     img_ids, eval_imgs = merge(self.img_ids, self.eval_imgs[iou_type])
[rank0]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/code/D-FINE-master/src/data/dataset/coco_eval.py", line 182, in merge
[rank0]:     all_eval_imgs = dist_utils.all_gather(eval_imgs)
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/code/D-FINE-master/src/misc/dist_utils.py", line 215, in all_gather
[rank0]:     torch.distributed.all_gather_object(data_list, data)
[rank0]:   File "/home/miniconda3/envs/detr/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/miniconda3/envs/detr/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 2494, in all_gather_object
[rank0]:     input_tensor, local_size = _object_to_tensor(obj, current_device, group)
[rank0]:                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/miniconda3/envs/detr/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 2409, in _object_to_tensor
[rank0]:     _pickler(f).dump(obj)
[rank0]: TypeError: cannot pickle 'faster_coco_eval.faster_eval_api_cpp.ImageEvaluation' object
```

**Comment by Peterande** [comment]
I've observed that the time it takes to accumulate evaluation results has really been accelerated a lot! But the wait time between these two lines of code seems to be longer, do you know the possible reasons?
`Averaged stats: `
`Accumulating evaluation results...`

**Comment by Peterande** [comment]
> I've observed that the time it takes to accumulate evaluation results has really been accelerated a lot! But the wait time between these two lines of code seems to be longer, do you know the possible reasons? `Averaged stats: ` `Accumulating evaluation results...`

After comparison, there is indeed an increase in speed. I would be happy to incorporate faster-coco-eval into D-FINE. But please help to check whether this problem is normal~THX!

**Comment by MiXaiLL76** [comment]
> > I've observed that the time it takes to accumulate evaluation results has really been accelerated a lot! But the wait time between these two lines of code seems to be longer, do you know the possible reasons? `Averaged stats: ` `Accumulating evaluation results...`
> 
> After comparison, there is indeed an increase in speed. I would be happy to incorporate faster-coco-eval into D-FINE. But please help to check whether this problem is normal~THX!

This is probably normal. In this interval, all the calculations that numpy does merge, which is generally not fast.

And also the execution of the accumulate function. (I have it written in C++, so I need to "pass" the accumulated data there)

**Pull request merged**
